export interface SearchItem {
  id: string
  title: string
  description: string
  content: string
  url: string
  category: "page" | "blog" | "feature" | "help" | "team"
  tags: string[]
  priority: number // Higher number = higher priority in results
  lastUpdated: string
}

export const searchData: SearchItem[] = [
  // Main Pages
  {
    id: "home",
    title: "BuildAIWeb - AI-Powered Mobile App Builder",
    description: "Build AI-generated mobile apps with just one prompt. The fastest way to go from idea to live app.",
    content: "AI mobile app builder artificial intelligence mobile development no-code prompt-driven app building",
    url: "/",
    category: "page",
    tags: ["home", "landing", "ai", "mobile app builder"],
    priority: 10,
    lastUpdated: "2025-06-16",
  },
  {
    id: "features",
    title: "Features - AI Mobile App Building Capabilities",
    description: "Explore powerful AI features including prompt-to-app, real-time editing, and intelligent mobile design.",
    content:
      "AI features prompt interface mobile app preview code generation real-time editing intelligent design responsive mobile",
    url: "/features",
    category: "page",
    tags: ["features", "ai", "capabilities", "demo"],
    priority: 9,
    lastUpdated: "2025-06-16",
  },
  {
    id: "about",
    title: "About BuildAIWeb - Our Story and Team",
    description: "Learn about our mission to democratize mobile app development through AI and meet our team.",
    content:
      "company story mission team values culture Sarah Chen Marcus Rodriguez Emily Watson David Kim Alex Thompson",
    url: "/about",
    category: "page",
    tags: ["about", "team", "company", "mission", "story"],
    priority: 8,
    lastUpdated: "2025-06-16",
  },
  {
    id: "dashboard",
    title: "AI Dashboard - Build Your Mobile App",
    description: "Interactive dashboard to create mobile apps with AI. Enter prompts and watch your app come to life.",
    content: "dashboard AI assistant prompt interface mobile app builder code preview real-time generation",
    url: "/dashboard",
    category: "page",
    tags: ["dashboard", "builder", "ai", "interactive"],
    priority: 10,
    lastUpdated: "2025-06-16",
  },
  {
    id: "pricing",
    title: "Pricing Plans - Choose Your Plan",
    description: "Flexible pricing plans from free starter to enterprise. Find the perfect plan for your mobile app needs.",
    content: "pricing plans free starter pro business enterprise subscription monthly annual",
    url: "/pricing",
    category: "page",
    tags: ["pricing", "plans", "subscription", "free", "pro"],
    priority: 9,
    lastUpdated: "2025-06-16",
  },
  {
    id: "blog",
    title: "Blog - AI Mobile App Development Insights",
    description: "Latest insights on AI mobile app development, tutorials, and industry trends.",
    content: "blog articles tutorials AI mobile app development insights trends best practices",
    url: "/blog",
    category: "page",
    tags: ["blog", "articles", "tutorials", "insights"],
    priority: 7,
    lastUpdated: "2025-06-16",
  },
  {
    id: "contact",
    title: "Contact Us - Get Help and Support",
    description: "Get in touch with our team, access support, or chat with our AI assistant.",
    content: "contact support help AI assistant chat form email phone",
    url: "/contact",
    category: "page",
    tags: ["contact", "support", "help", "chat"],
    priority: 8,
    lastUpdated: "2025-06-16",
  },

  // Blog Posts
  {
    id: "prompt-driven-app-building",
    title: "How Prompt-Driven App Building is Changing Mobile Development",
    description: "Discover how natural language prompts are revolutionizing mobile app development.",
    content:
      "prompt-driven development natural language AI mobile app development revolution accessibility technical complexity",
    url: "/blog/prompt-driven-app-building",
    category: "blog",
    tags: ["ai", "prompts", "mobile app development", "revolution"],
    priority: 8,
    lastUpdated: "2025-06-16",
  },
  {
    id: "mobile-layout-patterns-ai-engine",
    title: "10 Mobile Layout Patterns Trained into Our AI Engine",
    description: "Explore the most effective mobile app layout patterns that our AI has learned.",
    content: "layout patterns AI engine onboarding navigation dashboard chat e-commerce health fitness productivity",
    url: "/blog/mobile-layout-patterns-ai-engine",
    category: "blog",
    tags: ["design", "layouts", "patterns", "ai", "mobile"],
    priority: 7,
    lastUpdated: "2025-06-16",
  },
  {
    id: "figma-to-mobile-frontend-ai",
    title: "From Figma to Mobile Frontend with AI",
    description: "Learn how AI bridges the gap between mobile design and development.",
    content: "Figma mobile frontend AI design development handoff code generation responsive design",
    url: "/blog/figma-to-mobile-frontend-ai",
    category: "blog",
    tags: ["figma", "design", "frontend", "ai", "mobile"],
    priority: 7,
    lastUpdated: "2025-06-16",
  },
  {
    id: "ai-app-store-optimization",
    title: "AI-Powered ASO: How Our Engine Optimizes Every Generated App",
    description: "Discover how our AI automatically implements advanced App Store Optimization strategies.",
    content: "ASO optimization AI engine app store optimization content optimization performance mobile ranking",
    url: "/blog/ai-app-store-optimization",
    category: "blog",
    tags: ["aso", "optimization", "performance", "ai", "mobile"],
    priority: 7,
    lastUpdated: "2025-06-16",
  },
  {
    id: "future-of-mobile-development",
    title: "The Future of Mobile App Development: AI, No-Code, and Beyond",
    description: "Explore what's coming next in mobile app development as AI continues to evolve.",
    content: "future mobile app development AI no-code conversational development intelligent code evolution predictive UX",
    url: "/blog/future-of-mobile-development",
    category: "blog",
    tags: ["future", "ai", "no-code", "trends", "mobile"],
    priority: 6,
    lastUpdated: "2025-06-16",
  },

  // Features
  {
    id: "ai-prompt-interface",
    title: "AI Prompt Interface",
    description: "Natural language interface to describe and build your mobile app.",
    content: "prompt interface natural language AI chat mobile app description building",
    url: "/features#prompt-interface",
    category: "feature",
    tags: ["ai", "prompt", "interface", "natural language"],
    priority: 9,
    lastUpdated: "2025-06-16",
  },
  {
    id: "real-time-preview",
    title: "Real-time Mobile App Preview",
    description: "See your mobile app come to life as the AI builds it in real-time.",
    content: "real-time preview mobile app generation live updates instant feedback",
    url: "/features#real-time-preview",
    category: "feature",
    tags: ["preview", "real-time", "live", "generation"],
    priority: 8,
    lastUpdated: "2025-06-16",
  },
  {
    id: "code-generation",
    title: "Intelligent Code Generation",
    description: "AI generates clean, production-ready code for mobile apps following best practices.",
    content: "code generation AI clean production-ready best practices Kotlin Swift React Native Flutter",
    url: "/features#code-generation",
    category: "feature",
    tags: ["code", "generation", "ai", "clean", "production", "mobile"],
    priority: 8,
    lastUpdated: "2025-06-16",
  },
  {
    id: "responsive-design",
    title: "Automatic Responsive Mobile Design",
    description: "Every generated app is automatically optimized for all mobile devices.",
    content: "responsive design automatic mobile tablet optimization device compatibility",
    url: "/features#responsive-design",
    category: "feature",
    tags: ["responsive", "mobile", "design", "automatic"],
    priority: 7,
    lastUpdated: "2025-06-16",
  },

  // Team Members
  {
    id: "sarah-chen",
    title: "Sarah Chen - CEO & Co-Founder",
    description: "Former Google AI researcher leading BuildAIWeb's vision and strategy.",
    content: "Sarah Chen CEO co-founder Google AI researcher Stanford computer science machine learning",
    url: "/about#team",
    category: "team",
    tags: ["team", "ceo", "founder", "ai", "google"],
    priority: 6,
    lastUpdated: "2025-06-16",
  },
  {
    id: "marcus-rodriguez",
    title: "Marcus Rodriguez - CTO & Co-Founder",
    description: "Mobile architect with expertise in AI systems and scalable app infrastructure.",
    content: "Marcus Rodriguez CTO co-founder mobile architect AI systems scalable infrastructure MIT",
    url: "/about#team",
    category: "team",
    tags: ["team", "cto", "founder", "architecture", "infrastructure", "mobile"],
    priority: 6,
    lastUpdated: "2025-06-16",
  },
  {
    id: "emily-watson",
    title: "Emily Watson - Head of Product",
    description: "Product strategist focused on mobile user experience and AI-human interaction design.",
    content: "Emily Watson head product strategist user experience AI human interaction design mobile apps",
    url: "/about#team",
    category: "team",
    tags: ["team", "product", "ux", "design", "interaction", "mobile"],
    priority: 5,
    lastUpdated: "2025-06-16",
  },

  // Help & Support
  {
    id: "getting-started",
    title: "Getting Started with BuildAIWeb",
    description: "Quick start guide to building your first AI-generated mobile app.",
    content: "getting started guide tutorial first mobile app AI prompt tips best practices",
    url: "/help/getting-started",
    category: "help",
    tags: ["help", "tutorial", "getting started", "guide", "mobile"],
    priority: 8,
    lastUpdated: "2025-06-16",
  },
  {
    id: "prompt-tips",
    title: "Writing Effective Prompts",
    description: "Learn how to write prompts that generate better mobile apps.",
    content: "prompt tips effective writing better mobile apps AI instructions clear specific detailed",
    url: "/help/prompt-tips",
    category: "help",
    tags: ["help", "prompts", "tips", "writing", "mobile"],
    priority: 7,
    lastUpdated: "2025-06-16",
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting Common Issues",
    description: "Solutions to common problems and frequently asked questions about mobile app generation.",
    content: "troubleshooting common issues problems solutions FAQ mobile app generation",
    url: "/help/troubleshooting",
    category: "help",
    tags: ["help", "troubleshooting", "issues", "faq", "mobile"],
    priority: 6,
    lastUpdated: "2025-06-16",
  },
]

export const popularSearches = [
  "AI mobile app builder",
  "how to build mobile app with AI",
  "pricing plans",
  "dashboard",
  "features",
  "prompt tips",
  "responsive design",
  "code generation",
  "getting started",
  "contact support",
]

export const searchCategories = [
  { id: "all", label: "All Results", icon: "Search" },
  { id: "page", label: "Pages", icon: "FileText" },
  { id: "blog", label: "Blog Posts", icon: "BookOpen" },
  { id: "feature", label: "Features", icon: "Zap" },
  { id: "help", label: "Help & Support", icon: "HelpCircle" },
  { id: "team", label: "Team", icon: "Users" },
]