export interface SearchItem {
  id: string
  title: string
  description: string
  content: string
  url: string
  category: "page" | "blog" | "feature" | "help" | "team"
  tags: string[]
  priority: number // Higher number = higher priority in results
  lastUpdated: string
}

export const searchData: SearchItem[] = [
  // Main Pages
  {
    id: "home",
    title: "BuildAIWeb - AI-Powered Website Builder",
    description: "Build AI-generated websites with just one prompt. The fastest way to go from idea to live site.",
    content: "AI website builder artificial intelligence web development no-code prompt-driven site building",
    url: "/",
    category: "page",
    tags: ["home", "landing", "ai", "website builder"],
    priority: 10,
    lastUpdated: "2024-01-15",
  },
  {
    id: "features",
    title: "Features - AI Website Building Capabilities",
    description: "Explore powerful AI features including prompt-to-website, real-time editing, and intelligent design.",
    content:
      "AI features prompt interface website preview code generation real-time editing intelligent design responsive mobile",
    url: "/features",
    category: "page",
    tags: ["features", "ai", "capabilities", "demo"],
    priority: 9,
    lastUpdated: "2024-01-15",
  },
  {
    id: "about",
    title: "About BuildAIWeb - Our Story and Team",
    description: "Learn about our mission to democratize web development through AI and meet our team.",
    content:
      "company story mission team values culture Sarah Chen Marcus Rodriguez Emily Watson David Kim Alex Thompson",
    url: "/about",
    category: "page",
    tags: ["about", "team", "company", "mission", "story"],
    priority: 8,
    lastUpdated: "2024-01-15",
  },
  {
    id: "dashboard",
    title: "AI Dashboard - Build Your Website",
    description: "Interactive dashboard to create websites with AI. Enter prompts and watch your site come to life.",
    content: "dashboard AI assistant prompt interface website builder code preview real-time generation",
    url: "/dashboard",
    category: "page",
    tags: ["dashboard", "builder", "ai", "interactive"],
    priority: 10,
    lastUpdated: "2024-01-15",
  },
  {
    id: "pricing",
    title: "Pricing Plans - Choose Your Plan",
    description: "Flexible pricing plans from free starter to enterprise. Find the perfect plan for your needs.",
    content: "pricing plans free starter pro business enterprise subscription monthly annual",
    url: "/pricing",
    category: "page",
    tags: ["pricing", "plans", "subscription", "free", "pro"],
    priority: 9,
    lastUpdated: "2024-01-15",
  },
  {
    id: "blog",
    title: "Blog - AI Web Development Insights",
    description: "Latest insights on AI web development, tutorials, and industry trends.",
    content: "blog articles tutorials AI web development insights trends best practices",
    url: "/blog",
    category: "page",
    tags: ["blog", "articles", "tutorials", "insights"],
    priority: 7,
    lastUpdated: "2024-01-15",
  },
  {
    id: "contact",
    title: "Contact Us - Get Help and Support",
    description: "Get in touch with our team, access support, or chat with our AI assistant.",
    content: "contact support help AI assistant chat form email phone",
    url: "/contact",
    category: "page",
    tags: ["contact", "support", "help", "chat"],
    priority: 8,
    lastUpdated: "2024-01-15",
  },

  // Blog Posts
  {
    id: "prompt-driven-site-building",
    title: "How Prompt-Driven Site Building is Changing the Web",
    description: "Discover how natural language prompts are revolutionizing web development.",
    content:
      "prompt-driven development natural language AI web development revolution accessibility technical complexity",
    url: "/blog/prompt-driven-site-building",
    category: "blog",
    tags: ["ai", "prompts", "web development", "revolution"],
    priority: 8,
    lastUpdated: "2024-01-15",
  },
  {
    id: "layout-patterns-ai-engine",
    title: "10 Layout Patterns Trained into Our AI Engine",
    description: "Explore the most effective website layout patterns that our AI has learned.",
    content: "layout patterns AI engine hero landing page portfolio grid e-commerce restaurant corporate",
    url: "/blog/layout-patterns-ai-engine",
    category: "blog",
    tags: ["design", "layouts", "patterns", "ai"],
    priority: 7,
    lastUpdated: "2024-01-12",
  },
  {
    id: "figma-to-frontend-ai",
    title: "From Figma to Frontend with AI",
    description: "Learn how AI bridges the gap between design and development.",
    content: "Figma frontend AI design development handoff code generation responsive design",
    url: "/blog/figma-to-frontend-ai",
    category: "blog",
    tags: ["figma", "design", "frontend", "ai"],
    priority: 7,
    lastUpdated: "2024-01-10",
  },
  {
    id: "ai-seo-optimization",
    title: "AI-Powered SEO: How Our Engine Optimizes Every Generated Site",
    description: "Discover how our AI automatically implements advanced SEO strategies.",
    content: "SEO optimization AI engine technical SEO content optimization performance Core Web Vitals",
    url: "/blog/ai-seo-optimization",
    category: "blog",
    tags: ["seo", "optimization", "performance", "ai"],
    priority: 7,
    lastUpdated: "2024-01-08",
  },
  {
    id: "future-of-web-development",
    title: "The Future of Web Development: AI, No-Code, and Beyond",
    description: "Explore what's coming next in web development as AI continues to evolve.",
    content: "future web development AI no-code conversational development intelligent code evolution predictive UX",
    url: "/blog/future-of-web-development",
    category: "blog",
    tags: ["future", "ai", "no-code", "trends"],
    priority: 6,
    lastUpdated: "2024-01-05",
  },

  // Features
  {
    id: "ai-prompt-interface",
    title: "AI Prompt Interface",
    description: "Natural language interface to describe and build your website.",
    content: "prompt interface natural language AI chat website description building",
    url: "/features#prompt-interface",
    category: "feature",
    tags: ["ai", "prompt", "interface", "natural language"],
    priority: 9,
    lastUpdated: "2024-01-15",
  },
  {
    id: "real-time-preview",
    title: "Real-time Website Preview",
    description: "See your website come to life as the AI builds it in real-time.",
    content: "real-time preview website generation live updates instant feedback",
    url: "/features#real-time-preview",
    category: "feature",
    tags: ["preview", "real-time", "live", "generation"],
    priority: 8,
    lastUpdated: "2024-01-15",
  },
  {
    id: "code-generation",
    title: "Intelligent Code Generation",
    description: "AI generates clean, production-ready code following best practices.",
    content: "code generation AI clean production-ready best practices HTML CSS JavaScript React",
    url: "/features#code-generation",
    category: "feature",
    tags: ["code", "generation", "ai", "clean", "production"],
    priority: 8,
    lastUpdated: "2024-01-15",
  },
  {
    id: "responsive-design",
    title: "Automatic Responsive Design",
    description: "Every generated website is automatically optimized for all devices.",
    content: "responsive design automatic mobile tablet desktop optimization device compatibility",
    url: "/features#responsive-design",
    category: "feature",
    tags: ["responsive", "mobile", "design", "automatic"],
    priority: 7,
    lastUpdated: "2024-01-15",
  },

  // Team Members
  {
    id: "sarah-chen",
    title: "Sarah Chen - CEO & Co-Founder",
    description: "Former Google AI researcher leading BuildAIWeb's vision and strategy.",
    content: "Sarah Chen CEO co-founder Google AI researcher Stanford computer science machine learning",
    url: "/about#team",
    category: "team",
    tags: ["team", "ceo", "founder", "ai", "google"],
    priority: 6,
    lastUpdated: "2024-01-15",
  },
  {
    id: "marcus-rodriguez",
    title: "Marcus Rodriguez - CTO & Co-Founder",
    description: "Full-stack architect with expertise in AI systems and scalable web infrastructure.",
    content: "Marcus Rodriguez CTO co-founder full-stack architect AI systems scalable infrastructure MIT",
    url: "/about#team",
    category: "team",
    tags: ["team", "cto", "founder", "architecture", "infrastructure"],
    priority: 6,
    lastUpdated: "2024-01-15",
  },
  {
    id: "emily-watson",
    title: "Emily Watson - Head of Product",
    description: "Product strategist focused on user experience and AI-human interaction design.",
    content: "Emily Watson head product strategist user experience AI human interaction design",
    url: "/about#team",
    category: "team",
    tags: ["team", "product", "ux", "design", "interaction"],
    priority: 5,
    lastUpdated: "2024-01-15",
  },

  // Help & Support
  {
    id: "getting-started",
    title: "Getting Started with BuildAIWeb",
    description: "Quick start guide to building your first AI-generated website.",
    content: "getting started guide tutorial first website AI prompt tips best practices",
    url: "/help/getting-started",
    category: "help",
    tags: ["help", "tutorial", "getting started", "guide"],
    priority: 8,
    lastUpdated: "2024-01-15",
  },
  {
    id: "prompt-tips",
    title: "Writing Effective Prompts",
    description: "Learn how to write prompts that generate better websites.",
    content: "prompt tips effective writing better websites AI instructions clear specific detailed",
    url: "/help/prompt-tips",
    category: "help",
    tags: ["help", "prompts", "tips", "writing"],
    priority: 7,
    lastUpdated: "2024-01-15",
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting Common Issues",
    description: "Solutions to common problems and frequently asked questions.",
    content: "troubleshooting common issues problems solutions FAQ frequently asked questions",
    url: "/help/troubleshooting",
    category: "help",
    tags: ["help", "troubleshooting", "issues", "faq"],
    priority: 6,
    lastUpdated: "2024-01-15",
  },
]

export const popularSearches = [
  "AI website builder",
  "how to build website with AI",
  "pricing plans",
  "dashboard",
  "features",
  "prompt tips",
  "responsive design",
  "code generation",
  "getting started",
  "contact support",
]

export const searchCategories = [
  { id: "all", label: "All Results", icon: "Search" },
  { id: "page", label: "Pages", icon: "FileText" },
  { id: "blog", label: "Blog Posts", icon: "BookOpen" },
  { id: "feature", label: "Features", icon: "Zap" },
  { id: "help", label: "Help & Support", icon: "HelpCircle" },
  { id: "team", label: "Team", icon: "Users" },
]
